### ISSUE TITLE
Persist user in database

### ISSUE THREAD

**Issue by EmmanuelVella** [mazen/EtcpasswdOAuthBundle#13]
I'm using FOSUserBundle. After a successful provider  authentication, how can I persist the user in my database ?

**Comment by SkaveRat** [comment]
an example for this would be usefull

**Comment by jalonsoa** [comment]
Please, would be great !

**Comment by SkaveRat** [comment]
after trying around with verious methods, I don't think it's easy to use this with FOSUserBundle.

And as the maintainer doesn't respond about anything here, I'll mark this repo as dead for me. I'll have to live with email auth for now...

**Comment by jalonsoa** [comment]
Hi !
  finally, I can find a solution that work for me. I declare the fos_user as user provider on security.yml. Then  I wrote an AuthenticationProvider (based on AuthenticationProvider from etcpasswdoauthbundle), with  authenticate method thats make the trick.

```
    $data = $token->getResponse()->getJson();
    try {
        $user = $this->userProvider->loadUserByUsername($token->getUsername());
        // compare user properties with oauth data for updates
    } catch (UsernameNotFoundException $e) {
        // Create user with oauth data
    }
```

At last, configure the "etcpasswd_oauth.authentication.provider.oauth.class" as my AuthenticationProvider class 

I hope that this help you !

j

**Comment by SkaveRat** [comment]
Sweet, thanks. Helped me a lot. As I'm just beginning with Sf2, where can I override the configuration of the AuthProvider Class without doing it in the OAuthBundle?

**Comment by jalonsoa** [comment]
In your bundle. For example:

src/Acme/YourBundle/Security/Core/Authentication/Provider/OAuthProvider.php  (copy the OAuthProvider class from etcpasswd and develop from this)

Then in, your services.yml (or xml) src/Acme/YourBundle/Resources/config/services.yml define a parameter:

```
parameters:
    etcpasswd_oauth.authentication.provider.oauth.class: Acme\YourBundle\Security\Core\Authentication\Provider\OAuthProvider
```

j
